laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('a-escola', array('as' => 'a-escola', 'uses' => 'AEscolaController@index'));
Route::get('atendimento', array('as' => 'atendimento', 'uses' => 'AtendimentoController@index'));
Route::get('aulas-especificas', array('as' => 'aulas-especificas', 'uses' => 'AulasEspecificasController@index'));
Route::get('carta-fundadores', array('as' => 'carta-fundadores', 'uses' => 'CartaFundadoresController@index'));
Route::get('depoimentos', array('as' => 'depoimentos', 'uses' => 'DepoimentosController@index'));
Route::get('estrutura', array('as' => 'estrutura', 'uses' => 'EstruturaController@index'));
Route::get('proposta-pedagogica', array('as' => 'proposta-pedagogica', 'uses' => 'PropostaPedagogicaController@index'));
Route::get('relatorios-e-resultados', array('as' => 'relatorios-e-resultados', 'uses' => 'RelatoriosEResultadosController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::post('contato-trabalhar', array('as' => 'contato.trabalhar', 'uses' => 'ContatoController@trabalhar'));
Route::post('contato-indicar', array('as' => 'contato.indicar', 'uses' => 'ContatoController@indicar'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('painel/ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('a-escola', 'Painel\AEscolaController');
    Route::resource('atendimento', 'Painel\AtendimentoController');
    Route::resource('aulas-especificas', 'Painel\AulasEspecificasController');
    Route::resource('carta-fundadores', 'Painel\CartaFundadoresController');
    Route::resource('como-escolher', 'Painel\ComoEscolherController');
    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('depoimentos', 'Painel\DepoimentosController');
    Route::resource('estrutura', 'Painel\EstruturaController');
    Route::resource('estrutura-imagens', 'Painel\EstruturaImagensController');
    Route::resource('proposta-pedagogica', 'Painel\PropostaPedagogicaController');
    Route::resource('relatorios-e-resultados', 'Painel\RelatoriosEResultadosController');
	Route::resource('usuarios', 'Painel\UsuariosController');
	Route::resource('configuracoes', 'Painel\ConfiguracoesController', array(
		'only' => array('index', 'update')
	));
	Route::resource('seo', 'Painel\SEOController', array(
		'only' => array('index', 'edit', 'update')
	));
});

laravel/app/views/backend/templates/index.blade.php
<!DOCTYPE html>
<html lang="pt-BR" class="no-js">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="robots" content="index, follow" />
    <meta name="author" content="Trupe Design" />
    <meta name="copyright" content="2013 Trupe Design" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="shortcut icon" href="favicon-jandaia.ico">

    <title>Escola Equilíbrio - Painel Administrativo</title>
	<meta name="description" content="">
    <meta name="keywords" content="" />
    <meta property="og:title" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:type" content="website"/>
    <meta property="og:image" content="{{ asset('assets/images/layout/'); }}"/>
    <meta property="og:url" content="{{ Request::url() }}"/>
    <meta property="og:description" content=""/>

  	<meta property="fb:admins" content=""/>
  	<meta property="fb:app_id" content=""/>

	<base href="{{ route('painel.home') }}/">
	<script>var BASE = "{{ route('painel.home') }}"</script>

	<?=Assets::CSS(array(
		'vendor/reset-css/reset',
		'css/fontface/stylesheet',
		'vendor/bootstrap/dist/css/bootstrap.min',
		'css/painel/base'
	))?>

	@if(isset($css))
		<?=Assets::CSS(array($css))?>
	@endif

	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{asset('vendor/jquery/dist/jquery.min.js')}}"><\/script>')</script>

	@if(App::environment()=='local')
		<?=Assets::JS(array('js/vendor/modernizr/modernizr', 'vendor/less.js/dist/less-1.6.2.min'))?>
	@else
		<?=Assets::JS(array('js/vendor/modernizr/modernizr'))?>
	@endif

</head>
	<body @if(Route::currentRouteName() == 'painel.login') class="body-painel-login" @else class="body-painel" @endif >

		@if(Route::currentRouteName() != 'painel.login')

			<nav class="navbar navbar-default">
				<div class="navbar-inner">
					<a href="{{URL::route('painel.home')}}" title="Página Inicial" class="navbar-brand">Escola Equilíbrio</a>

					<ul class="nav navbar-nav">

						<li @if(str_is('painel.home*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.home')}}" title="Início">Início</a>
						</li>

						<li @if(str_is('*como-escolher*', Route::currentRouteName())) class="active" @endif >
							<a href="{{ URL::route('painel.como-escolher.index') }}" title="Como Escolher uma Escola">Como Escolher uma Escola</a>
						</li>

						<li class="dropdown @if(str_is('*carta-fundadores*', Route::currentRouteName()) || str_is('*a-escola*', Route::currentRouteName())) active @endif">
							<a href="#" title="Com Dropdown" class="dropdown-toggle" data-toggle="dropdown">A Escola <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{ URL::route('painel.a-escola.index') }}" title="A Escola - Texto">Texto</a></li>
								<li><a href="{{ URL::route('painel.carta-fundadores.index') }}" title="A Escola - Carta dos Fundadores">Carta dos Fundadores</a></li>
							</ul>
						</li>

						<li @if(str_is('*proposta-pedagogica*', Route::currentRouteName())) class="active" @endif >
							<a href="{{ URL::route('painel.proposta-pedagogica.index') }}" title="Proposta Pedagógica">Proposta Pedagógica</a>
						</li>

						<li class="dropdown @if(str_is('*estrutura*', Route::currentRouteName())) active @endif">
							<a href="#" title="Com Dropdown" class="dropdown-toggle" data-toggle="dropdown">Estrutura <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{ URL::route('painel.estrutura.index') }}" title="Estrutura - Texto">Texto</a></li>
								<li><a href="{{ URL::route('painel.estrutura-imagens.index') }}" title="Estrutura - Imagens">Imagens</a></li>
							</ul>
						</li>

						<li @if(str_is('*relatorios-e-resultados*', Route::currentRouteName())) class="active" @endif >
							<a href="{{ URL::route('painel.relatorios-e-resultados.index') }}" title="Relatórios e resultados">Relatórios e resultados</a>
						</li>

						<li @if(str_is('*depoimentos*', Route::currentRouteName())) class="active" @endif >
							<a href="{{ URL::route('painel.depoimentos.index') }}" title="Depoimentos">Depoimentos</a>
						</li>

						<li @if(str_is('*atendimento*', Route::currentRouteName())) class="active" @endif >
							<a href="{{ URL::route('painel.atendimento.index') }}" title="Atendimento">Atendimento</a>
						</li>

						<li @if(str_is('*aulas-especificas*', Route::currentRouteName())) class="active" @endif >
							<a href="{{ URL::route('painel.aulas-especificas.index') }}" title="Aulas Específicas">Aulas Específicas</a>
						</li>

						<li @if(str_is('*contato*', Route::currentRouteName())) class="active" @endif >
							<a href="{{ URL::route('painel.contato.index') }}" title="Contato">Contato</a>
						</li>

						<li class="dropdown @if(str_is('*usuarios*', Route::currentRouteName()) || str_is('*configuracoes*', Route::currentRouteName()) || str_is('*seo*', Route::currentRouteName())) active @endif">
							<a href="#" title="Com Dropdown" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.configuracoes.index')}}" title="Configurações">Configurações</a></li>
								<li><a href="{{URL::route('painel.seo.index')}}" title="SEO">SEO</a></li>
								<li class="divider"></li>
								<li><a href="{{URL::route('painel.usuarios.index')}}" title="Usuários do Painel">Usuários</a></li>
								<li><a href="{{URL::route('painel.off')}}" title="Logout">Logout</a></li>
							</ul>
						</li>

					</ul>
				</div>
			</nav>

		@endif

		<div class="main {{ 'main-'.str_replace('.', '-', Route::currentRouteName()) }}">
			@yield('conteudo')
		</div>

		<footer>
			<div class="container">
				<a href="http://www.trupe.net" target="_blank" title="Criação de Sites : Trupe Agência Criativa">© Criação de Sites : Trupe Agência Criativa</a>
			</div>
		</footer>

		@if(Route::currentRouteName() == 'painel.login')
			<?=Assets::JS(array(
				'vendor/jquery-ui/ui/minified/jquery-ui.min',
				'vendor/bootbox/bootbox',
				'vendor/ckeditor/ckeditor',
				'vendor/ckeditor/adapters/jquery',
				'vendor/bootstrap/dist/js/bootstrap.min',
				'js/painel/login'
			))?>
		@else
			<?=Assets::JS(array(
				'vendor/jquery-ui/ui/minified/jquery-ui.min',
				'vendor/bootbox/bootbox',
				'vendor/ckeditor/ckeditor',
				'vendor/ckeditor/adapters/jquery',
				'vendor/bootstrap/dist/js/bootstrap.min',
				'js/painel/painel'
			))?>
		@endif

	</body>
</html>