laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('a-escola', array('as' => 'a-escola', 'uses' => 'AEscolaController@index'));
Route::get('atendimento', array('as' => 'atendimento', 'uses' => 'AtendimentoController@index'));
Route::get('aulas-especificas', array('as' => 'aulas-especificas', 'uses' => 'AulasEspecificasController@index'));
Route::get('carta-fundadores', array('as' => 'carta-fundadores', 'uses' => 'CartaFundadoresController@index'));
Route::get('depoimentos', array('as' => 'depoimentos', 'uses' => 'DepoimentosController@index'));
Route::get('estrutura', array('as' => 'estrutura', 'uses' => 'EstruturaController@index'));
Route::get('proposta-pedagogica', array('as' => 'proposta-pedagogica', 'uses' => 'PropostaPedagogicaController@index'));
Route::get('relatorios-e-resultados', array('as' => 'relatorios-e-resultados', 'uses' => 'RelatoriosEResultadosController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::post('contato-trabalhar', array('as' => 'contato.trabalhar', 'uses' => 'ContatoController@trabalhar'));
Route::post('contato-indicar', array('as' => 'contato.indicar', 'uses' => 'ContatoController@indicar'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('painel/ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('a-escola', 'Painel\AEscolaController');
    Route::resource('atendimento', 'Painel\AtendimentoController');
    Route::resource('aulas-especificas', 'Painel\AulasEspecificasController');
    Route::resource('carta-fundadores', 'Painel\CartaFundadoresController');
    Route::resource('como-escolher', 'Painel\ComoEscolherController');
    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('depoimentos', 'Painel\DepoimentosController');
    Route::resource('estrutura', 'Painel\EstruturaController');
    Route::resource('estrutura-imagens', 'Painel\EstruturaImagensController');
    Route::resource('proposta-pedagogica', 'Painel\PropostaPedagogicaController');
    Route::resource('relatorios-e-resultados', 'Painel\RelatoriosEResultadosController');
	Route::resource('usuarios', 'Painel\UsuariosController');
	Route::resource('configuracoes', 'Painel\ConfiguracoesController', array(
		'only' => array('index', 'update')
	));
	Route::resource('seo', 'Painel\SEOController', array(
		'only' => array('index', 'edit', 'update')
	));
});

laravel/app/models/RelatoriosEResultados.php
<?php

class RelatoriosEResultados extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'relatorios_e_resultados';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

}

laravel/app/controllers/RelatoriosEResultadosController.php
<?php

use \RelatoriosEResultados;

class RelatoriosEResultadosController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index()
	{
		$this->layout->with('contato_rodape', Contato::first());
		$this->layout->with('como_escolher', ComoEscolher::first());

		$this->layout->content = View::make('frontend.relatorioseresultados')->with('texto', RelatoriosEResultados::first());
	}

}

laravel/app/controllers/painel/RelatoriosEResultadosController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \RelatoriosEResultados;

class RelatoriosEResultadosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.relatorioseresultados.index')->with('registros', RelatoriosEResultados::all());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return Redirect::route('painel.relatorios-e-resultados.index');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		return Redirect::route('painel.relatorios-e-resultados.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		return Redirect::route('painel.relatorios-e-resultados.index');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.relatorioseresultados.edit')->with('registro', RelatoriosEResultados::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = RelatoriosEResultados::find($id);

		$object->texto_relatorio = Input::get('texto_relatorio');
		$object->texto_resultados = Input::get('texto_resultados');		
		
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto alterado com sucesso.');
			return Redirect::route('painel.relatorios-e-resultados.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));	

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		return Redirect::route('painel.relatorios-e-resultados.index');
	}

}

laravel/app/views/backend/relatorioseresultados/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Texto - Relatório e Resultados
        </h2>  

		{{ Form::open( array('route' => array('painel.relatorios-e-resultados.update', $registro->id), 'files' => false, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputTextoRelatorios">Texto Relatórios</label>
					<textarea name="texto_relatorio" id="inputTextoRelatorios" class="form-control">{{$registro->texto_relatorio}}</textarea>
				</div>

				<div class="form-group">
					<label for="inputTextoResultados">Texto Resultados</label>
					<textarea name="texto_resultados" id="inputTextoResultados" class="form-control">{{$registro->texto_resultados}}</textarea>
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.relatorios-e-resultados.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/relatorioseresultados/index.blade.php
@section('conteudo')

<div class="container">

	@if(Session::has('sucesso'))
	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

	@if($errors->any())
		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
	@endif

	<h2>
  		Relatórios e Resultados
	</h2>

  	<table class="table table-striped table-bordered table-hover">

  		<thead>
    		<tr>
                <th>Texto Relatórios</th>
                <th>Texto Resultados</th>
          		<th><span class="glyphicon glyphicon-cog"></span></th>
        	</tr>
  		</thead>

  		<tbody>
    	@foreach ($registros as $registro)

        	<tr class="tr-row" id="row_{{ $registro->id }}">
                <td>{{ Str::words( strip_tags($registro->texto_relatorio), 15) }}</td>
                <td>{{ Str::words( strip_tags($registro->texto_resultados), 15) }}</td>
                <td class="crud-actions">
            		<a href="{{ URL::route('painel.relatorios-e-resultados.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>
          		</td>
        	</tr>

    	@endforeach
  		</tbody>

	</table>

</div>

@stop