laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('a-escola', array('as' => 'a-escola', 'uses' => 'AEscolaController@index'));
Route::get('atendimento', array('as' => 'atendimento', 'uses' => 'AtendimentoController@index'));
Route::get('aulas-especificas', array('as' => 'aulas-especificas', 'uses' => 'AulasEspecificasController@index'));
Route::get('carta-fundadores', array('as' => 'carta-fundadores', 'uses' => 'CartaFundadoresController@index'));
Route::get('depoimentos', array('as' => 'depoimentos', 'uses' => 'DepoimentosController@index'));
Route::get('estrutura', array('as' => 'estrutura', 'uses' => 'EstruturaController@index'));
Route::get('proposta-pedagogica', array('as' => 'proposta-pedagogica', 'uses' => 'PropostaPedagogicaController@index'));
Route::get('relatorios-e-resultados', array('as' => 'relatorios-e-resultados', 'uses' => 'RelatoriosEResultadosController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::post('contato-trabalhar', array('as' => 'contato.trabalhar', 'uses' => 'ContatoController@trabalhar'));
Route::post('contato-indicar', array('as' => 'contato.indicar', 'uses' => 'ContatoController@indicar'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('painel/ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('a-escola', 'Painel\AEscolaController');
    Route::resource('atendimento', 'Painel\AtendimentoController');
    Route::resource('aulas-especificas', 'Painel\AulasEspecificasController');
    Route::resource('carta-fundadores', 'Painel\CartaFundadoresController');
    Route::resource('como-escolher', 'Painel\ComoEscolherController');
    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('depoimentos', 'Painel\DepoimentosController');
    Route::resource('estrutura', 'Painel\EstruturaController');
    Route::resource('estrutura-imagens', 'Painel\EstruturaImagensController');
    Route::resource('proposta-pedagogica', 'Painel\PropostaPedagogicaController');
    Route::resource('relatorios-e-resultados', 'Painel\RelatoriosEResultadosController');
	Route::resource('usuarios', 'Painel\UsuariosController');
	Route::resource('configuracoes', 'Painel\ConfiguracoesController', array(
		'only' => array('index', 'update')
	));
	Route::resource('seo', 'Painel\SEOController', array(
		'only' => array('index', 'edit', 'update')
	));
});

laravel/app/models/Depoimentos.php
<?php

class Depoimentos extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'depoimentos';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

}

laravel/app/controllers/DepoimentosController.php
<?php

use \Depoimentos;

class DepoimentosController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index()
	{
		$this->layout->with('contato_rodape', Contato::first());
		$this->layout->with('como_escolher', ComoEscolher::first());

		$this->layout->content = View::make('frontend.depoimentos')->with('depoimentos', Depoimentos::orderBy('ordem', 'asc')->get());
																 
	}

}

laravel/app/controllers/painel/DepoimentosController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Image, \File, \Hash, \Depoimentos;

class DepoimentosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.depoimentos.index')->with('registros', Depoimentos::orderBy('ordem', 'asc')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.depoimentos.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Depoimentos;

		$object->legenda = Input::get('legenda');

		if(Input::hasFile('imagem')){

			$imagem = Input::file('imagem');

			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/depoimentos/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));
			
			$object->imagem = $filename;

			$imagem->move('assets/images/depoimentos/', $filename);

			ini_set('memory_limit','256M');

			Image::make($file_path)->resize(400, null, true, false)->save('assets/images/depoimentos/thumbs/'.$filename, 100);
		}else{
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao Inserir Imagem!'));
		}
		
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Depoimentos criado com sucesso.');
			return Redirect::route('painel.depoimentos.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao Inserir Depoimento!.'.$e->getMessage()));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.depoimentos.edit')->with('registro', Depoimentos::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Depoimentos::find($id);

		$object->legenda = Input::get('legenda');

		if(Input::hasFile('imagem')){

			$imagem = Input::file('imagem');

			$random = '';
			do
			{
			    $filename = Str::slug($imagem->getClientOriginalName()).'_'.$random.'.'.File::extension($imagem->getClientOriginalName());
			    $file_path = 'assets/images/depoimentos/'.$filename;
			    $random = Str::random(6);
			}
			while (File::exists($file_path));
			
			$object->imagem = $filename;

			$imagem->move('assets/images/depoimentos/', $filename);

			ini_set('memory_limit','256M');

			Image::make($file_path)->resize(400, null, true, false)->save('assets/images/depoimentos/thumbs/'.$filename, 100);
		}
		
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Depoimento alterado com sucesso.');
			return Redirect::route('painel.depoimentos.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao Alterar Depoimento!.'));	

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Depoimentos::find($id);
		@unlink('assets/images/depoimentos/'.$object->imagem);
		@unlink('assets/images/depoimentos/thumbs/'.$object->imagem);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Depoimento removido com sucesso.');

		return Redirect::route('painel.depoimentos.index');
	}

}

laravel/app/views/backend/depoimentos/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Alterar Depoimento
        </h2>  

		{{ Form::open( array('route' => array('painel.depoimentos.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
		    		@if($registro->imagem)
		    			<img src="{{ asset('assets/images/depoimentos/thumbs/'.$registro->imagem) }}"><br>
		    			<a href="{{ asset('assets/images/depoimentos/'.$registro->imagem) }}" target="_blank" title="Ver tamanho original">Ver tamanho original</a><br><br>
		    		@endif
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>

				<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" value="{{ $registro->legenda }}">
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.depoimentos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/depoimentos/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Depoimento
        </h2>  

		<form action="{{URL::route('painel.depoimentos.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>

				<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" @if(Session::has('formulario')) value="{{ Session::get('formulario')->legenda[0] }}" @endif>
				</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.depoimentos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/depoimentos/index.blade.php
@section('conteudo')

<div class="container">

	@if(Session::has('sucesso'))
       <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

	@if($errors->any())
		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
	@endif

	<h2>
  		Depoimentos <a href="{{ URL::route('painel.depoimentos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span>  Adicionar Depoimento</a>
	</h2>

	<table class="table table-striped table-bordered table-hover table-sortable" data-tabela="depoimentos">
        
        <thead>
    		<tr>
            	<th>Ordenar</th>
            	<th>Imagem</th>
            	<th>Legenda</th>
      			<th><i class="icon-cog"></i></th>
    		</tr>
  		</thead>

  		<tbody>
  		@if(sizeof($registros) > 0)
	    	@foreach ($registros as $registro)

	        	<tr class="tr-row" id="row_{{ $registro->id }}">
	              	<td class="move-actions"><a href="#" class="btn btn-info btn-move btn-small">mover</a></td>
	              	<td><img src="{{ asset('assets/images/depoimentos/thumbs/'.$registro->imagem) }}"></td>
	              	<td>{{ $registro->legenda }}</td>
	          		<td class="crud-actions">
	            		<a href="{{ URL::route('painel.depoimentos.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

	            	   {{ Form::open(array('route' => array('painel.depoimentos.destroy', $registro->id), 'method' => 'delete')) }}
	                        <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
	                   {{ Form::close() }}
	          		</td>
	        	</tr>

	    	@endforeach
	    @else
            <tr>
              	<td colspan="4">
              	<h3>Nenhum Registro Encontrado</h3>
            	</td>
            </tr>
        @endif
  		</tbody>

    </table>
    
</div>

@stop